# runnerdeployment.yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: 3runnerdeploy
spec:
  replicas: 4
  template:
    spec:
      repository: paugh7/Testing
      env: []
