---
# Source: actions-runner-controller/templates/auth_proxy_role_binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: runner-actions-runner-controller-proxy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: runner-actions-runner-controller-proxy
subjects:
- kind: ServiceAccount
  name: runner-actions-runner-controller
  namespace: default
