---
# Source: actions-runner-controller/templates/leader_election_role_binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: runner-actions-runner-controller-leader-election
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: runner-actions-runner-controller-leader-election
subjects:
- kind: ServiceAccount
  name: runner-actions-runner-controller
  namespace: default
