---
# Source: actions-runner-controller/templates/runner_viewer_role.yaml
# permissions to do viewer runners.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: runner-actions-runner-controller-runner-viewer
rules:
- apiGroups:
  - actions.summerwind.dev
  resources:
  - runners
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - actions.summerwind.dev
  resources:
  - runners/status
  verbs:
  - get
