---
# Source: actions-runner-controller/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: runner-actions-runner-controller
  namespace: default
  labels:
    helm.sh/chart: actions-runner-controller-0.15.1
    app.kubernetes.io/name: actions-runner-controller
    app.kubernetes.io/instance: runner
    app.kubernetes.io/version: "0.20.3"
    app.kubernetes.io/managed-by: Helm
