---
# Source: actions-runner-controller/templates/webhook_service.yaml
apiVersion: v1
kind: Service
metadata:
  name: runner-actions-runner-controller-webhook
  namespace: default
  labels:
    helm.sh/chart: actions-runner-controller-0.15.1
    app.kubernetes.io/name: actions-runner-controller
    app.kubernetes.io/instance: runner
    app.kubernetes.io/version: "0.20.3"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: 9443
      protocol: TCP
      name: https
  selector:
    app.kubernetes.io/name: actions-runner-controller
    app.kubernetes.io/instance: runner
